# Generated by Django 5.0.1 on 2024-06-18 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0002_rename_manga_fiction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiction',
            old_name='story',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='fiction',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='fiction',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiction',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fiction',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
