# Generated by Django 5.0.1 on 2024-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_name'),
        ('fiction', '0002_rename_manga_fiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_fictions',
            field=models.ManyToManyField(blank=True, related_name='favorite_fictions', to='fiction.fiction'),
        ),
        migrations.AddField(
            model_name='user',
            name='finished_fictions',
            field=models.ManyToManyField(blank=True, related_name='finished_fictions', to='fiction.fiction'),
        ),
        migrations.AddField(
            model_name='user',
            name='ongoing_fictions',
            field=models.ManyToManyField(blank=True, related_name='ongoing_fictions', to='fiction.fiction'),
        ),
        migrations.AddField(
            model_name='user',
            name='wallpaper',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
