# Generated by Django 5.0.1 on 2024-06-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manga',
            new_name='Fiction',
        ),
    ]
