# Generated by Django 5.0.1 on 2024-06-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0004_fiction_creator_alter_fiction_author'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiction',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='genre.genre'),
        ),
    ]
