# Generated by Django 5.0.1 on 2024-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0005_fiction_genre'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiction',
            name='genre',
            field=models.ManyToManyField(blank=True, to='genre.genre'),
        ),
    ]
