# Generated by Django 5.0.1 on 2024-06-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiction', '0003_rename_story_fiction_about_rename_name_fiction_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('chapter_number', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('fiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='fiction.fiction')),
            ],
            options={
                'ordering': ['chapter_number'],
                'unique_together': {('fiction', 'chapter_number')},
            },
        ),
    ]
