# Generated by Django 5.0.1 on 2024-06-29 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
        ('fiction', '0006_alter_fiction_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='fiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiction.fiction'),
        ),
    ]
