# Generated by Django 5.0.1 on 2024-06-30 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0002_alter_chapter_fiction'),
        ('fiction', '0007_rename_poster_fiction_poster_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='fiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='fiction.fiction'),
        ),
    ]
